version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql_data/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CHANGETHIS

  wordpress:
    container_name: wordpress
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./wordpress_data/:/var/www/html/
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql

  haproxy:
    container_name: haproxy
    image: haproxy
    depends_on:
      - wordpress
    links:
      - wordpress
      - phpmyadmin
    ports:
      - "443:443"
    volumes:
      - ./haproxy_data/:/usr/local/etc/haproxy
      - ./letsencrypt/live/lucasgambini.dev/bundle.pem:/etc/ssl/certs/bundle.pem
    restart: always
